---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.DRONE_WALL_NAME}}
spec:
  egress:
  - {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-external
  podSelector:
    matchLabels:
      name: {{.DRONE_WALL_NAME}}
  policyTypes:
  - Ingress
  - Egress
